import type { Region } from './types'

export const regions: Region[] = [
  {
    id: 'puer-city',
    name: 'Пуэр',
    chinese: '普洱',
    category: 'city',
    x: 33,
    y: 58,
    description: 'Исторический центр сбора, торговли и именования чая; современное название охватывает город и обширный округ.',
    sourceIds: ['zhang-2013', 'yunnan-2023'],
  },
  {
    id: 'jingmai',
    name: 'Цзинмай',
    chinese: '景迈山',
    category: 'landscape',
    x: 28,
    y: 78,
    description: 'Старые чайные леса и деревни, где земледелие встроено в лесной ландшафт; объект Всемирного наследия ЮНЕСКО.',
    sourceIds: ['unesco-jingmai'],
  },
  {
    id: 'youle',
    name: 'Юлэ',
    chinese: '攸乐',
    category: 'mountain',
    x: 54,
    y: 68,
    description: 'Одно из шести названий, которые «南詔備考» приводит в передаче цинской компиляции.',
    sourceIds: ['zhao-facsimile-pku'],
  },
  {
    id: 'gedeng',
    name: 'Гэдэн',
    chinese: '革登',
    category: 'mountain',
    x: 66,
    y: 58,
    description: 'Гора древнего списка; в поздних хрониках связана с легендой о Чжугэ Ляне.',
    sourceIds: ['zhao-facsimile-pku', 'puer-wuhou'],
  },
  {
    id: 'yibang',
    name: 'Ибан',
    chinese: '倚邦',
    category: 'mountain',
    x: 72,
    y: 49,
    description: 'Ибан входит в старый список гор. Чай Э в 1926 году называет Ибан в пассаже, где характеризует пуэр как тёплый по свойству и насыщенный по вкусу.',
    sourceIds: ['zhao-facsimile-pku', 'fantianlu-vol18-scan'],
  },
  {
    id: 'mangzhi',
    name: 'Манчжи',
    chinese: '莽枝',
    category: 'mountain',
    x: 76,
    y: 61,
    description: 'Одно из шести названий, сохранённых в «南詔備考» и переданных цинской компиляцией.',
    sourceIds: ['zhao-facsimile-pku'],
  },
  {
    id: 'manzhuan',
    name: 'Маньчжуань',
    chinese: '蛮专 / 蛮砖',
    category: 'mountain',
    x: 82,
    y: 70,
    description: 'Одно из шести названий старого списка. Формула о вкусе принадлежит общему пассажу Чай Э 1926 года, а не дегустационной заметке Чжао о Маньчжуане.',
    sourceIds: ['zhao-facsimile-pku', 'fantianlu-vol18-scan'],
  },
  {
    id: 'mansa',
    name: 'Маньса',
    chinese: '慢撒',
    category: 'mountain',
    x: 88,
    y: 55,
    description: 'Одно из шести названий, приведённых «南詔備考» в передаче цинской компиляции.',
    sourceIds: ['zhao-facsimile-pku'],
  },
]
