import type { Region } from './types'

export const regions: Region[] = [
  {
    id: 'puer-city',
    name: 'Пуэр',
    chinese: '普洱',
    category: 'city',
    x: 33,
    y: 58,
    description: 'Исторический центр сбора, торговли и именования чая; современное название охватывает город и обширный округ.',
    sourceIds: ['zhang-2013', 'yunnan-2023'],
  },
  {
    id: 'jingmai',
    name: 'Цзинмай',
    chinese: '景迈山',
    category: 'landscape',
    x: 28,
    y: 78,
    description: 'Старые чайные леса и деревни, где земледелие встроено в лесной ландшафт; объект Всемирного наследия ЮНЕСКО.',
    sourceIds: ['unesco-jingmai'],
  },
  {
    id: 'youle',
    name: 'Юлэ',
    chinese: '攸乐',
    category: 'mountain',
    x: 54,
    y: 68,
    description: 'Одна из исторических шести чайных гор к востоку от Ланьцанцзяна.',
    sourceIds: ['zhao-1765'],
  },
  {
    id: 'gedeng',
    name: 'Гэдэн',
    chinese: '革登',
    category: 'mountain',
    x: 66,
    y: 58,
    description: 'Гора древнего списка; в поздних хрониках связана с легендой о Чжугэ Ляне.',
    sourceIds: ['zhao-1765', 'puer-wuhou'],
  },
  {
    id: 'yibang',
    name: 'Ибан',
    chinese: '倚邦',
    category: 'mountain',
    x: 72,
    y: 49,
    description: 'Исторический центр производства и торговли, особо отмеченный Чжао Сюэминем за вкус чая.',
    sourceIds: ['zhao-1765'],
  },
  {
    id: 'mangzhi',
    name: 'Манчжи',
    chinese: '莽枝',
    category: 'mountain',
    x: 76,
    y: 61,
    description: 'Часть восточной группы старых чайных гор Сишуанбаньны.',
    sourceIds: ['zhao-1765'],
  },
  {
    id: 'manzhuan',
    name: 'Маньчжуань',
    chinese: '蛮专 / 蛮砖',
    category: 'mountain',
    x: 82,
    y: 70,
    description: 'Одна из шести гор, чай которой исторический текст выделяет рядом с Ибаном.',
    sourceIds: ['zhao-1765'],
  },
  {
    id: 'mansa',
    name: 'Маньса',
    chinese: '慢撒',
    category: 'mountain',
    x: 88,
    y: 55,
    description: 'Историческая гора, часто рассматриваемая вместе с более поздним чайным регионом Иу.',
    sourceIds: ['zhao-1765', 'zhang-2013'],
  },
]
